{% set name = "click" %}
{% set version = "8.1.6" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/click-{{ version }}.tar.gz
  sha256: 48ee849951919527a045bfe3bf7baa8a959c423134e1a5b98c05c20ba75a1cbd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [win]
  string: unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [unix]

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - colorama   # [win]
    - __win      # [win]
    - __unix     # [unix]

test:
  requires:
    - pip
  imports:
    - click
  commands:
    - pip check

about:
  home: https://palletsprojects.com/p/click/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Composable command line interface toolkit
  description: |
    Click is a Python package for creating beautiful command line interfaces
    in a composable way with as little code as necessary. It's the "Command
    Line Interface Creation Kit". It's highly configurable but comes with
    sensible defaults out of the box.

    It aims to make the process of writing command line tools quick and fun
    while also preventing any frustration caused by the inability to
    implement an intended CLI API.

    Click in three points:

    -   Arbitrary nesting of commands
    -   Automatic help page generation
    -   Supports lazy loading of subcommands at runtime
  dev_url: https://github.com/pallets/click/
  doc_url: https://click.palletsprojects.com/

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
