{% set version = "8.0.4" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/click/click-{{ version }}.tar.gz
  sha256: 8458d7b1287c5fb128c90e23381cf99dcde74beaf6c7ff6384ce84d6fe090adb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - colorama  # [win]
    - importlib-metadata  # [py<38]

test:
  requires:
    - pip
  imports:
    - click
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]

about:
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Python composable command line interface toolkit
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
