{% set version = "8.0.0" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/click/click-{{ version }}.tar.gz
  sha256: 7d8c289ee437bcb0316820ccee14aefcb056e58d31830ecab8e47eda6540e136

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - click

about:
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Python composable command line interface toolkit
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
